const productos=[
    {   
        id:'001',
        nombre:'MacBook M1 AIR 13',
        foto:"",
        precio:"",
        memoria:256,
        descripcion:'M1 Chip 7‑core GPU /8GB',
        color: ['space'],
        estado:'En stock',
        tendencia:true,
        marca:'apple',
        categoria:'macbook'},
    {   
        id:'002',
        nombre:'MacBook AIR 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["space","silver","gold"],
        descripcion:'M1 Chip 8 core GPU /8GB',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'003',
        nombre:'MacBook M1 PRO 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'M1 Chip 8‑core GPU /8GB ',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'004',
        nombre:'MacBook AIR 13',
        foto:"",
        precio:"",
        memoria:[216,512],
        color:["space"],
        descripcion:'M1 Chip 7- core GPU /16GB ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'005',
        nombre:'MacBook AIR 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'M1 Chip 7- core GPU /16GB ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'006',
        nombre:'MacBook PRO 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'M1 Chip 8- core GPU /16GB ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'007',
        nombre:'MacBook AIR M2 13',
        foto:"",
        precio:"",
        memoria:256,
        color:["midnight"],
        descripcion:'8 core gpu, 8gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'008',
        nombre:'MacBook AIR M2 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["midnight"],
        descripcion:'10 core gpu, 8gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {   
        id:'009',
        nombre:'MacBook PRO M2 13',
        foto:"",
        precio:"",
        memoria:256,
        color:["space","silver"],
        descripcion:'10 core gpu, 8gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {
        id:'010',
        nombre:'PRO 13-inch M2',
        foto:"",
        precio:"",
        memoria:256,
        color:["silver"],
        descripcion:'8c CPU 10c GPU 8gb',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    {
        id:'011',
        nombre:'PRO 13-inch M2',
        foto:"",
        precio:"",
        memoria:256,
        color:["silver"],
        descripcion:'Retina Display, 8c CPU, 10c GPU 8gb ram, Touch Bar, Backlit Keyboard, Face Time HD Camera',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},

    {
        id:'012',
        nombre:'PRO M2 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["silver"],
        descripcion:'8c CPU, 10c GPU 8gb ram - Spanish Keyboard MNEQ3E/A',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
        

    {
        id:'013',
        nombre:'AIR M2 13.6-inch',
        foto:"",
        precio:"",
        memoria:256,
        color:["midnight"],
        descripcion:'Liquid Retina Display, 8gb ram , ssd',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},

    {
        id:'014',
        nombre:'AIR M2 13.6-inch',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'8c CPU, 10c GPU 16gb ram- Spanish Keyboard',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},

    {
        id:'015',
        nombre:'PRO M2 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["space","silver"],
        descripcion:'10 core gpu, 8gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},

    {
        id:'016',
        nombre:'PRO M2 13',
        foto:"",
        precio:"",
        memoria:512,
        color:["silver"],
        descripcion:'10 core gpu, 16gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    
    {
        id:'017',
        nombre:'PRO M2 13',
        foto:"",
        precio:"",
        memoria:1000,
        color:["silver"],
        descripcion:'10 core gpu, 16gb ram',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},

    {
        id:'018',
        nombre:'PRO M1 14',
        foto:"",
        precio:"",
        memoria:512,
        color:["space","silver"],
        descripcion:'8 core CPU, 14 core GPU, 16GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},
    
    {
        id:'019',
        nombre:'PRO M1 14',
        foto:"",
        precio:"",
        memoria:512,
        color:["space","silver"],
        descripcion:'8 core CPU, 14 core GPU, 16GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},  
    
    {
        id:'020',
        nombre:'PRO M1 14',
        foto:"",
        precio:"",
        memoria:1000,
        color:["silver"],
        descripcion:'8 core CPU, 14 core GPU, 16GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'}, 
    
    {
        id:'021',
        nombre:'PRO M1 16',
        foto:"",
        precio:"",
        memoria:512,
        color:["space","silver"],
        descripcion:'8 core CPU, 14 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'}, 
    
    {
        id:'022',
        nombre:'PRO M1 16',
        foto:"",
        precio:"",
        memoria:1000,
        color:["space"],
        descripcion:'10 CORE CPU, 16 CORE GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},     
    
    {
        id:'023',
        nombre:'PRO M1 14 32GB',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'8 core CPU, 14 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},        
    
    {
        id:'024',
        nombre:'PRO M1 14 32GB',
        foto:"",
        precio:"",
        memoria:1000,
        color:["space"],
        descripcion:'10 CORE CPU, 16 CORE GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},      
    
    {
        id:'025',
        nombre:'PRO M1 16 32Gb',
        foto:"",
        precio:"",
        memoria:512,
        color:["space"],
        descripcion:'10 CORE CPU, 16 CORE GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},    
    
    {
        id:'026',
        nombre:'PRO M1 16 32Gb',
        foto:"",
        precio:"",
        memoria:1000,
        color:["space"],
        descripcion:'10 CORE CPU, 16 CORE GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},     
    
    {
        id:'027',
        nombre:'PRO M1 MAX 16',
        foto:"",
        precio:"",
        memoria:1000,
        color:["space"],
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"apple",
        categoria:'macbook'},        
    
    //productos apple fin

    //Gafas VR
    {
        id:'028',
        nombre:'Vive Cosmos Elite Virtual Reality System',
        foto:"",
        precio:"",
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"HTC",
        categoria:'vr'}, 

    {
        id:'029',
        nombre:'Vive Pro 2 Headset Only',
        foto:"",
        precio:"",
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"HTC",
        categoria:'vr'}, 
    

    {
        id:'030',
        nombre:'Vive Pro Eye Office Full System - PC',
        foto:"",
        precio:"",
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"HTC",
        categoria:'vr'}, 
    

    {
        id:'031',
        nombre:'Quest 2',
        foto:"",
        precio:"",
        memoria:256,
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"Meta",
        categoria:'vr'}, 


    {
        id:'032',
        nombre:'Quest 2',
        foto:"",
        precio:"",
        memoria:128,
        descripcion:'With 10 core CPU, 24 core GPU, 32GB RAM',
        estado:'En stock',
        tendencia:false,
        marca:"Meta",
        categoria:'vr'}, 

    //Notebooks
    {
        id:'033',
        nombre:'Notebook Asus X512JA-211.VBGB',
        foto:"",
        precio:"217,739.50",
        descripcion:'15.6¨ FHD TOUCHSCREEN👆/I7-1065G7/8GB-256GB SSD + 1TB HDD/WIN 10/SLATE GRAY',
        estado:'En stock',
        tendencia:false,
        marca:"Asus",
        categoria:'notebook'},
        

    {
        id:'034',
        nombre:'Notebook Asus X515EA-212.V15TB',
        foto:"",
        precio:"123,310.00",
        descripcion:'15.6 FHD TOUCHSCREEN/I3-1115G4/8GB-256GB SSD/WIN 11/SLATE GREY',
        estado:'En stock',
        tendencia:false,
        marca:"Asus",
        categoria:'notebook'},


    {
        id:'035',
        nombre:'Notebook Asus X515JA-212.V15BB-11',
        foto:"",
        precio:"111,628.00",
        descripcion:'15.6" HD/I3-1005G1/8GB-256GB SSD/TECLADO INGLÉS- PAD NUMÉRICO/WIN 10',
        estado:'En stock',
        tendencia:false,
        marca:"Asus",
        categoria:'notebook'},


    //placas de video

    {
        id:'036',
        nombre:'RTX 2060 12GB REVEL DUAL FAN (12GB GDDR6)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'037',
        nombre:'RTX 2060 12GB REVEL DUAL FAN (12GB GDDR6)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'038',
        nombre:'RTX 3060 GAMING Z TRIO 12G (12GB GDDR6)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'039',
        nombre:'RTX 3060 TI VENTUS 3X 8G OC (8GB GDDR6)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'040',
        nombre:'RTX 3070 VENTUS 2X 8GB ',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'041',
        nombre:'RTX 3070 VENTUS 3X 8GB OC',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'042',
        nombre:'RTX 3070 TI VENTUS 3X 8G OC (8GB GDDR6X)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'043',
        nombre:'RTX 3070 TI XLR8 GAMING REVEL EPIC-X RGB 3xFAN 8GB GDDR6X',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"PNY",
        categoria:'mineria'},


    {
        id:'044',
        nombre:'RTX 3080 LHR UPRISING TRIPLE FAN 12GB GDDR6X',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"PNY",
        categoria:'mineria'},


    {
        id:'045',
        nombre:'RTX 3080 TI XLR8 GAMING REVEL EPIC-X RGB 3xFAN 12GB GDDR6X',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"PNY",
        categoria:'mineria'},

    
    {
        id:'046',
        nombre:'RTX 3090 VENTUS 3X 24G OC (2476)',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"MSI",
        categoria:'mineria'},

    {
        id:'047',
        nombre:'RTX 3090 TI XLR8 GAMING UPRISING EPIC-X RGB 3xFAN 24GB GDDR6X',
        foto:"",
        precio:"",
        descripcion:'',
        estado:'En stock',
        tendencia:false,
        marca:"PNY",
        categoria:'mineria'},



//MONITORES

{
    id:'048',
    nombre:'ASUS - Monitor para juegos IPS de 1ms FreeSync Extreme Low Motion Blur Eye Care DisplayPort HDMI VGA, Negro',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"ASUS",
    categoria:'monitores'},

{
    id:'049',
    nombre:'Monitor AOC para videojuegos, curvado, sin marco, FHD 1ms VA 24"',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"AOC",
    categoria:'monitores'},


{
    id:'050',
    nombre:'Monitor SAMSUNG FHD de 24 pulgadas con diseño sin bisel, LS24R350FHNXZA, gris azul oscuro',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"samsung",
    categoria:'monitores'},


{
    id:'051',
    nombre:'Monitor LG 34GP83A-B 34´´ 21: 9 UltraGear Curvo QHD (3440 x 1440) 1 ms Nano IPS con 160Hz - Negro',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"LG",
    categoria:'monitores'},

{
    id:'052',
    nombre:'Monitor LG 32GN650-B Monitor de 32´´ QHD (2560 x 1440), frecuencia de actualización de 165 Hz, 1 ms MBR, HDR 10, sRGB 95%, Negro',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"LG",
    categoria:'monitores'},

{
    id:'053',
    nombre:'Monitor LG 34GL750-B 21: 9 Ultragear Monitor curvado para juegos compatible con Wfhd (2560 X 1080) IPS 144Hz G-SYNC, 34 pulgadas, negro',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"LG",
    categoria:'monitores'},


{
    id:'054',
    nombre:'Monitor SAMSUNG de juegos de 49 pulgadas, monitor curvado ultra-ancho, 240 Hz 1 ms, Quantum Mini LED, G-Sync, monitor de altura ajustable, HDR 2000, Odyssey Neo G9, G95NA (LS49AG952NXZA)',
    foto:"",
    precio:"",
    descripcion:'',
    estado:'En stock',
    tendencia:false,
    marca:"samsung",
    categoria:'monitores'},
    ];

export default productos